name: app_tcc_unip
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  http: ^0.13.3
  flutter_dotenv: ^5.0.2
  shared_preferences: ^2.0.7
  jwt_decoder: ^2.0.1
  intl: ^0.17.0
  community_material_icon: ^5.9.55
  image_picker: ^0.8.4+1
  sqflite: ^2.0.0+4
  flutter_chat_bubble: ^2.0.0
  stomp_dart_client: ^0.4.3
  badges: ^2.0.1
  path_provider: ^2.0.4
  image: ^3.0.8
  flutter_local_notifications: ^9.0.1
  multi_select_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/logo150.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env